export const TECH_DATA = {
  hollowPurple:        { name: 'Hollow Purple',                        character: 'Gojo Satoru',   isDomain: false, color: '#a333ff' },
  infiniteVoid:        { name: 'Infinite Void',                        character: 'Gojo Satoru',   isDomain: true,  domainName: 'Unlimited Void',                      color: '#ffffff' },
  red:                 { name: 'Cursed Technique Reversal: Red',       character: 'Gojo Satoru',   isDomain: false, color: '#ff0000' },
  malevolentShrine:    { name: 'Malevolent Shrine',                    character: 'Ryomen Sukuna', isDomain: true,  domainName: 'Malevolent Shrine',                   color: '#ff3300' },
  blackFlash:          { name: 'Black Flash',                          character: 'Yuji Itadori',  isDomain: false, color: '#ff0055' },
  idleTransfiguration: { name: 'Idle Transfiguration',                 character: 'Mahito',        isDomain: true,  domainName: 'Self-Embodiment of Perfection',       color: '#00ffcc' },
  boogieWoogie:        { name: 'Boogie Woogie',                        character: 'Todo Aoi',      isDomain: false, color: '#ffff00' },
  tenShadows:          { name: 'Ten Shadows',                          character: 'Megumi Fushiguro', isDomain: true, domainName: 'Chimera Shadow Garden',             color: '#aaaaaa' },
  disasterFlames:      { name: 'Disaster Flames',                      character: 'Jogo',          isDomain: true,  domainName: 'Horizon of the Captivating Skandha', color: '#ff6600' },
  cursedSpeech:        { name: 'Cursed Speech',                        character: 'Inumaki Toge',  isDomain: false, color: '#0066ff' },
  construction:        { name: 'Construction',                         character: 'Mai / Yorozu',  isDomain: false, color: '#999999' },
  comedy:              { name: 'Comedy',                               character: 'Takaba',        isDomain: false, color: '#ff00ff' },
  bloodManipulation:   { name: 'Blood Manipulation',                   character: 'Choso / Kamo',  isDomain: false, color: '#880000' },
  ratioTechnique:      { name: 'Ratio Technique',                      character: 'Nanami',        isDomain: false, color: '#ccff00' },
  jackpot:             { name: 'Jackpot',                              character: 'Hakari',        isDomain: true,  domainName: 'Idle Death Gamble',                  color: '#00ffff' },
  skyManipulation:     { name: 'Sky Manipulation',                     character: 'Uro',           isDomain: false, color: '#aaaaff' },
  neutral:             { name: 'Neutral State',                        character: '',              isDomain: false, color: '#00ffff' },
  none:                { name: '',                                     character: '',              isDomain: false, color: '#00ffff' },
};
